/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CLIENT.UI;

import CLIENT.DTO.ExamDTO;
import CLIENT.DTO.UserDTO;

import javax.swing.*;

/**
 *
 * @author nguye
 */
public class BeginExam extends javax.swing.JPanel {

     private int DEFALUT_WIDTH;
     private ExamDTO exam;
     private UserDTO user;
    public BeginExam() {
          this.setSize(1090, 750);
        initComponents();
    }

    public BeginExam(int width) {
         DEFALUT_WIDTH = width;
        initComponents();
        this.setSize(this.DEFALUT_WIDTH - 200, 750);
        initComponents();
    }
     public BeginExam(int width, ExamDTO exam,UserDTO user){
         DEFALUT_WIDTH = width;
         this.exam=exam;
         this.user=user;
        initComponents();
        this.setSize(this.DEFALUT_WIDTH - 200, 750);
        initComponents();
         setInfoExam();
         init();
    }
     private void init(){
         lbIMGMain.setIcon(new ImageIcon("./src/main/java/CLIENT/UI/img/imgQuzizz.jpg"));
     }
    private void setInfoExam(){
        txtClassRoom.setText(exam.getClass_room());
        txtExamID.setText(String.valueOf(exam.getId()));
        txtQuantity.setText(String.valueOf(exam.getQuantity()));
        txtSubject.setText(String.valueOf(exam.getSubject()));
        txtTime.setText(String.valueOf(exam.getTotal_time()));
        txtUserID.setText(String.valueOf(exam.getId()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HEADER = new javax.swing.JPanel();
        lbSoLuong1 = new javax.swing.JLabel();
        pInfoExam = new javax.swing.JPanel();
        txtSubject = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnBeginDoingExam = new javax.swing.JButton();
        txtTime = new javax.swing.JTextField();
        txtClassRoom = new javax.swing.JTextField();
        txtUserID = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtExamID = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lbIMGMain = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        HEADER.setBackground(new java.awt.Color(204, 0, 51));

        lbSoLuong1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbSoLuong1.setForeground(new java.awt.Color(255, 255, 255));
        lbSoLuong1.setText("THÔNG TIN ĐỀ THI");
        lbSoLuong1.setToolTipText("CHỌN ĐỀ THI");

        javax.swing.GroupLayout HEADERLayout = new javax.swing.GroupLayout(HEADER);
        HEADER.setLayout(HEADERLayout);
        HEADERLayout.setHorizontalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HEADERLayout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(lbSoLuong1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HEADERLayout.setVerticalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSoLuong1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        pInfoExam.setBackground(new java.awt.Color(255, 255, 255));
        pInfoExam.setForeground(new java.awt.Color(0, 0, 153));

        txtSubject.setEditable(false);
        txtSubject.setBackground(new java.awt.Color(255, 255, 255));
        txtSubject.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtSubject.setForeground(new java.awt.Color(0, 0, 153));
        txtSubject.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Mã Đề Thi :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Tiêu Đề");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Mã Phòng Thi");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Số Lượng Câu Hỏi");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Thời Gian");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Người Tạo");

        btnBeginDoingExam.setBackground(new java.awt.Color(0, 153, 0));
        btnBeginDoingExam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBeginDoingExam.setForeground(new java.awt.Color(255, 255, 255));
        btnBeginDoingExam.setText("Bắt Đầu Thi");
        btnBeginDoingExam.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true));
        btnBeginDoingExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnBeginDoingExamActionPerformed(evt);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
            }
        });

        txtTime.setEditable(false);
        txtTime.setBackground(new java.awt.Color(255, 255, 255));
        txtTime.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtTime.setForeground(new java.awt.Color(0, 0, 153));
        txtTime.setBorder(null);

        txtClassRoom.setEditable(false);
        txtClassRoom.setBackground(new java.awt.Color(255, 255, 255));
        txtClassRoom.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtClassRoom.setForeground(new java.awt.Color(0, 0, 153));
        txtClassRoom.setBorder(null);

        txtUserID.setEditable(false);
        txtUserID.setBackground(new java.awt.Color(255, 255, 255));
        txtUserID.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtUserID.setForeground(new java.awt.Color(0, 0, 153));
        txtUserID.setBorder(null);
        txtUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIDActionPerformed(evt);
            }
        });

        txtQuantity.setEditable(false);
        txtQuantity.setBackground(new java.awt.Color(255, 255, 255));
        txtQuantity.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtQuantity.setForeground(new java.awt.Color(0, 0, 153));
        txtQuantity.setBorder(null);

        txtExamID.setEditable(false);
        txtExamID.setBackground(new java.awt.Color(255, 255, 255));
        txtExamID.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtExamID.setForeground(new java.awt.Color(0, 0, 153));
        txtExamID.setBorder(null);

        btnBack.setBackground(new java.awt.Color(255, 204, 0));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 51, 51));
        btnBack.setText("Quay Lại");
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pInfoExamLayout = new javax.swing.GroupLayout(pInfoExam);
        pInfoExam.setLayout(pInfoExamLayout);
        pInfoExamLayout.setHorizontalGroup(
            pInfoExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInfoExamLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(lbIMGMain, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(pInfoExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pInfoExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pInfoExamLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pInfoExamLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pInfoExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pInfoExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnBeginDoingExam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtClassRoom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                .addComponent(txtTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                .addComponent(txtUserID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                .addComponent(txtExamID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)))))
                .addGap(124, 124, 124))
        );
        pInfoExamLayout.setVerticalGroup(
            pInfoExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInfoExamLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pInfoExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClassRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pInfoExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pInfoExamLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pInfoExamLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(txtExamID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(pInfoExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTime)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pInfoExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pInfoExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pInfoExamLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pInfoExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(pInfoExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBeginDoingExam, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
            .addGroup(pInfoExamLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbIMGMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HEADER, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pInfoExam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HEADER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pInfoExam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBeginDoingExamActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_btnBeginDoingExamActionPerformed
        ManageExam.openTakeExamPanel(exam,user);
    }//GEN-LAST:event_btnBeginDoingExamActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt)  {//GEN-FIRST:event_btnBackActionPerformed
     ManageExam.openChooenExamPanel(user);       
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HEADER;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBeginDoingExam;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbIMGMain;
    private javax.swing.JLabel lbSoLuong1;
    private javax.swing.JPanel pInfoExam;
    private javax.swing.JTextField txtClassRoom;
    private javax.swing.JTextField txtExamID;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSubject;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtUserID;
    // End of variables declaration//GEN-END:variables
}
