/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CLIENT.UI;

import CLIENT.BLL.ExamBLL;
import CLIENT.DTO.ExamDTO;
import CLIENT.DTO.UserDTO;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.Vector;

/**
 *
 * @author nguye
 */
public class ChooseExam extends javax.swing.JPanel {

    /**
     * Creates new form ChooseExam
     */
     private int DEFALUT_WIDTH;
     private UserDTO user;
      private ExamBLL bllEx=new ExamBLL();
      private DefaultTableModel modelExam;
    public ChooseExam() throws Exception {
          this.setSize(1090, 750);
        initComponents();
        init();
    }

    public ChooseExam(int width)  {
         DEFALUT_WIDTH = width;
        initComponents();
        this.setSize(this.DEFALUT_WIDTH - 200, 750);
        initComponents();
        init();
    }
     public ChooseExam(int width,UserDTO user)  {
         DEFALUT_WIDTH = width;
         this.user=user;
        initComponents();
        this.setSize(this.DEFALUT_WIDTH - 200, 750);
        initComponents();
        init();
    }
     private void init() {
            loadDataExam();
           lbIconHeader.setIcon(new ImageIcon("./src/main/java/CLIENT/UI/img/icons8-quiz-96.png")); // NOI18N
           lbIMGMain.setIcon(new ImageIcon("./src/main/java/CLIENT/UI/img/icons8-quizizz-150.png"));
     }
       private void loadDataExam() {
        try {
                bllEx.loadDSExam("LOAD_EXAM");
                ArrayList<ExamDTO> res=ExamBLL.getListExam();
            insertHeaderExam();
            outModelExam(modelExam, ExamBLL.getListExam());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không Thể Lấy thông Tin Đề Thi ",
                    "Thông Báo Lỗi", JOptionPane.ERROR_MESSAGE);
        }

    }
     private void insertHeaderExam() {
        Vector header = new Vector();
        header.add("ID");
        header.add("Tiêu Đề");
        header.add("Phòng");
        header.add("Lượng Câu Hỏi");
        header.add("Thời gian");
        header.add("Người tạo");
        //if (model.getRowCount()==0)
        modelExam = new DefaultTableModel(header, 0);
    }
      private void outModelExam(DefaultTableModel model, ArrayList<ExamDTO> courseinstructor) // Xuất ra Table từ ArrayList
    {
        Vector data;
        model.setRowCount(0);
        for (ExamDTO ex : courseinstructor) {
            data = new Vector();
            data.add(ex.getId());
            data.add(ex.getSubject());
            data.add(ex.getClass_room());
            data.add(ex.getQuantity());
            data.add(ex.getTotal_time());
            data.add(ex.getUserID());

            model.addRow(data);
        }
        tbExam.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HEADER = new javax.swing.JPanel();
        lbSoLuong1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbExam = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lbIconHeader = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lbIMGMain = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        HEADER.setBackground(new java.awt.Color(30, 188, 196));

        lbSoLuong1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbSoLuong1.setForeground(new java.awt.Color(255, 255, 255));
        lbSoLuong1.setText("DANH SÁCH ĐỀ THI");
        lbSoLuong1.setToolTipText("CHỌN ĐỀ THI");

        javax.swing.GroupLayout HEADERLayout = new javax.swing.GroupLayout(HEADER);
        HEADER.setLayout(HEADERLayout);
        HEADERLayout.setHorizontalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HEADERLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbSoLuong1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(394, 394, 394))
        );
        HEADERLayout.setVerticalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSoLuong1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        tbExam.setBackground(new java.awt.Color(255, 255, 204));
        tbExam.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        tbExam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbExam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbExam.setRowHeight(30);
        tbExam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbExamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbExam);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 51, 102));
        jTextArea1.setRows(5);
        jTextArea1.setText("Hướng Dẫn: \n\n- Chọn vào đề thi muốn thi trong bảng bên dưới.\n- Hệ thống sẽ chuyển đến phần thi dành cho bạn.\n");
        jTextArea1.setBorder(null);
        jTextArea1.setOpaque(false);
        jTextArea1.setRequestFocusEnabled(false);
        jTextArea1.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lbIMGMain, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(lbIconHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(lbIconHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 19, Short.MAX_VALUE))
            .addComponent(lbIMGMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HEADER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HEADER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbExamMouseClicked(java.awt.event.MouseEvent evt)  {//GEN-FIRST:event_tbExamMouseClicked
        int i = tbExam.getSelectedRow();
        int id=-1;
        if (i >= 0) {
            id =Integer.parseInt(tbExam.getModel().getValueAt(i, 0).toString());
            ManageExam.openBeginExamPanel(bllEx.findExamByID(id),user);

        }
    }//GEN-LAST:event_tbExamMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HEADER;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbIMGMain;
    private javax.swing.JLabel lbIconHeader;
    private javax.swing.JLabel lbSoLuong1;
    private javax.swing.JTable tbExam;
    // End of variables declaration//GEN-END:variables
}
